id: I23BA1940
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:37:37.523923+00:00
last_modified: 2022-12-14 10:37:37.523928+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2019-08-20T09:40:47.842Z'
  creationid: SE
  eft-text-id: UT22084-062-010
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_210-The_Rice_Seedling-v1
bases:
  E8EF:
    source_metadata: null
    order: 1
    base_file: E8EF.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
